const daftarPegawai = [
"Syam Wuryani",
"Septian Darma Putra Siagian",
"Dardi",
"Imi Fitriah",
"Joko Juniarto",
"Kartika Ari Pratama",
"Wahyu Ari Wibowo",
"Dwi Sukma Oktaviani",
"Robin Hood",
"Triyoni Rakhmawati",
"Leni Marlina",
"Mimi Wijayanti",
"Darwanti",
"Marvikatin",
"Sunardi",
"Yosi Yomarta",
"Nova Rustanti",
"Nanik Kurnianingsih",
"Halbet Julianto",
"Nasirwan",
"Ricky Casanopa",
"Elsa Refika Pertiwi",
"Mohamad Ridwan Soleh Ruslan Syafi'i",
"Erlita Aryani",
"Dwickey Nurfitriani Mardhotillah",
"Dwi Septi Aryani",
"Diah Saraswati",
"Geinte Bella Lagenda",
"Tri Artarina",
"Rita Effriani",
"Sri Martini",
"Elvis Srirahmi",
"Dilin",
"Gusti Abdi Rahman",
"Nyayu Yulia",
"Eko Agusfian",
"Sasdiarman",
"Yuristen Hadi",
"Surya Raymond",
"Suyanto",
"Jang Doralok",
"Wahyu Sukamto",
"Gumanto",
"Edi Riskando",
"Martini",
"Lilik Nur Rokhmah",
"Restu Dwi Kurniaty",
"Elli Nurhayati",
"Muhammad Muhlisin",
"Arianda Nugra Gamas",
"Nami Purwanti Amd. Kep",
"Radial Fajri",
"Rahmat Kevin Praditia S.Stat",
"Annisa Ayu Lestari S.I.Kom",
"Nada Nur Sella, S.I.Kom",
"Sherly Yuniarsi, S.I.kom",
"Susilo S.Ip",
"Afri Wiranda",
"Elysabet Rigensi",
"Sarif Rendi Susanto",
"Subhan",
"Lenkis Mahayati",
"Halidi Hermanto",
"Irna Rosalina",
"Rista Andela",
"Yulistia Pradini Astari",
"Nginda Annisa Aiyun",
"Dede Rahman",
"Yudi Novian",
"Azuan Zoni",
"Supono",
"Miskum",
"Febri Prawiro",
"Andi Saputra",
"Odiarman Hasibuan",
"Andi Susandri",
"Iqbal Ramadhan",
"Ilham Hidayat",
"Jesi Duanty"
];
